// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.Encodinator;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.Encoder.PIDSourceParameter;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLefty;
    public static SpeedController driveTrainRighty;
    public static RobotDrive driveTrainRobotDrive21;
    public static Encoder driveTrainEncoderR;
    public static Encoder driveTrainEncoderL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLefty = new Jaguar(1, 1);
	LiveWindow.addActuator("Drive Train", "Lefty", (Jaguar) driveTrainLefty);
        
        driveTrainRighty = new Jaguar(1, 2);
	LiveWindow.addActuator("Drive Train", "Righty", (Jaguar) driveTrainRighty);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainLefty, driveTrainRighty);
	
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(0.75);
        

        driveTrainEncoderR = new Encoder(1, 1, 1, 2, false, EncodingType.k4X);
	LiveWindow.addSensor("Drive Train", "Encoder R", driveTrainEncoderR);
        driveTrainEncoderR.setDistancePerPulse(0.04177);
        driveTrainEncoderR.setReverseDirection(true);
        driveTrainEncoderR.setPIDSourceParameter(PIDSourceParameter.kDistance);
        driveTrainEncoderR.start();
        driveTrainEncoderL = new Encoder(1, 3, 1, 4, false, EncodingType.k4X);
	LiveWindow.addSensor("Drive Train", "Encoder L", driveTrainEncoderL);
        driveTrainEncoderL.setDistancePerPulse(0.04177);
        driveTrainEncoderL.setPIDSourceParameter(PIDSourceParameter.kDistance);
        driveTrainEncoderL.start();
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
